image: Visual Studio 2017
clone_folder: c:\projects\kickstart-salt
install:
<<<<<<< HEAD
  - ps: ls c:\python37
  - ps: c:\python37\bin\pip.exe -m install pyinstaller pyyaml deep_merge requests
=======
  - ps: ls c:\python36
  - ps: c:\python36\bin\pip.exe -m install pyinstaller pyyaml deep_merge requests
>>>>>>> 42637357ef95298f8955b08ea0fd2d957642a5a4
  - ps: pyinstaller c:\projects\kickstart-salt.py --onefile
  - ps: ls c:\projects\kickstart-salt
