image: Visual Studio 2017

clone_folder: c:\projects\kickstart_salt
install:
  - cmd: set PATH=%PATH%;C:\python37\Scripts\
  # - ps: c:\python37\python.exe -m pip install pyinstaller pyyaml deep_merge requests
  - ps: c:\python37\python.exe c:\projects\kickstart_salt\setup.py install

build_script: pyinstaller c:\projects\kickstart_salt\kickstart_salt.py --onefile

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
