image: Visual Studio 2017

environment:
  TSD_GITHUB_TOKEN:
    secure: tdeHjQ/eql1WYbTzrLhR6SnCeAPwEkRQDZPAXZownmaVTra81/TUWpiXc5zvMzE4

only_commits:
  files:
    - kickstart_salt_imports.py
    - kickstart_salt.py

clone_folder: c:\projects\kickstart_salt
install:
  - cmd: set PATH=%PATH%;C:\python37\Scripts\
  - ps: c:\python37\python.exe -m pip install pyinstaller pyyaml deep_merge requests
  - ps: ls

build_script: pyinstaller c:\projects\kickstart_salt\kickstart_salt.py --onefile

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

deploy:
  release: kickstart_salt-$(appveyor_repo_branch)-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: tdeHjQ/eql1WYbTzrLhR6SnCeAPwEkRQDZPAXZownmaVTra81/TUWpiXc5zvMzE4
  artifact: c:\projects\kickstart_salt\dist\kickstart-salt
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
