image: Visual Studio 2017
clone_folder: c:\projects\kickstart-salt
install:
  - cmd: set PATH=%PATH%;C:\python37\Scripts\
  - ps: c:\python37\python.exe -m pip install pyinstaller pyyaml deep_merge requests

build_script: pyinstaller c:\projects\kickstart-salt\kickstart-salt.py --onefile
