image: Visual Studio 2017

environment:
  TSD_GITHUB_TOKEN:
    secure: tdeHjQ/eql1WYbTzrLhR6SnCeAPwEkRQDZPAXZownmaVTra81/TUWpiXc5zvMzE4

only_commits:
  files:
    - kickstart_salt_imports.py
    - kickstart_salt.py

clone_folder: c:\projects\kickstart_salt
install:
  - cmd: set PATH=%PATH%;C:\python37\Scripts\
  - ps: c:\python37\python.exe -m pip install pyinstaller pyyaml deep_merge requests

build_script: pyinstaller c:\projects\kickstart_salt\kickstart_salt.py --onefile

on_finish:
  - ps: ls c:\projects\kickstart_salt\dist

artifacts:
  - path: c:\projects\kickstart_salt\dist\
    name: Releases

deploy:
  release: kickstart_salt-$(appveyor_repo_branch)-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: tdeHjQ/eql1WYbTzrLhR6SnCeAPwEkRQDZPAXZownmaVTra81/TUWpiXc5zvMzE4
  artifact: kickstart_salt.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
