version: 2.0
jobs:
 build:
   docker:
     - image: python:3.7.2
   steps:
     - checkout
     - run:
         name: Install kickstart-salt dependencies
         command: |
           pip install pyinstaller
           pip install yaml
           pip install deep_merge
           pip install requests
