version: 2.0
jobs:
 build:
   docker:
     - image: python:3.7.2
   steps:
     - checkout
     - run:
         name: Install kickstart-salt dependencies
         command: |
           pip install pyinstaller
           pip install pyyaml
           pip install deep_merge
           pip install requests
     - run:
         name: Build kickstart-salt binary
         command: |
           pyinstaller ./kickstart-salt.py --onefile
     - run:
         name: list artifacts
         command: |
           ls -la
