version: 2.0
jobs:
 build:
   docker:
     - image: python:3.7.2
   steps:
     - checkout
     - run:
         name: Install PyInstaller
         command: |
           sudo apt-get update && sudo apt-get install pyinstaller
